version: '2.1'
orbs:
  flutter: circleci/flutter@1.2.0
  codecov: codecov/codecov@3.2.3
workflows:
  test:
    jobs:
      - flutter/unit_test:
          version: 2.2.3
            post-steps:
            - upload/codecov
