version: '2.1'
orbs:
  coveralls: coveralls/coveralls@1.0.6
  flutter: circleci/flutter@1.1.0
jobs:
  build-project:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test --coverage
  uploadd:
    docker:
      -image: 'circleci/node:10.0.0'
    steps:
      - upload/coveralls
workflows:
  upload-to-codecov:
    jobs:
      - build-project
      - uploadd:
        requires:
          - build-project
