name: Frontend workflow

on:[push]

jobs:
  build:
    - name: Flutter action
      uses: subosito/flutter-action@v2.6.2
    - name: Install requirements
      run: flutter pub get
    - name: Run tests and collect coverage
      run: flutter test --coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2
